// Copyright 2022 Giammarco Boscaro. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.17

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:docusign_esignature_flutter_sdk/api.dart';
import 'package:test/test.dart';

// tests for Jurisdiction
void main() {
  // final instance = Jurisdiction();

  group('test Jurisdiction', () {
    // When **true,** the seal can be generated by the platform.
    // String allowSystemCreatedSeal
    test('to test the property `allowSystemCreatedSeal`', () async {
      // TODO
    });

    // When **true,** the seal can be uploaded by the user.
    // String allowUserUploadedSeal
    test('to test the property `allowUserUploadedSeal`', () async {
      // TODO
    });

    // When **true,** the notary's `comissionId` appears in the seal.
    // String commissionIdInSeal
    test('to test the property `commissionIdInSeal`', () async {
      // TODO
    });

    // The county of the jurisdiction.
    // String county
    test('to test the property `county`', () async {
      // TODO
    });

    // When **true,** the county name appears in the seal.
    // String countyInSeal
    test('to test the property `countyInSeal`', () async {
      // TODO
    });

    // When **true,** this jurisdiction is enabled.
    // String enabled
    test('to test the property `enabled`', () async {
      // TODO
    });

    // The ID of the jurisdiction. The following jurisdictions are supported:  -  `5 - California` -  `6 - Colorado` -  `9 - Florida` -  `10 - Georgia` -  `12 - Idaho` -  `13 - Illinois` -  `14 - Indiana` -  `15 - Iowa` -  `17 - Kentucky` -  `23 - Minnesota` -  `25 - Missouri` -  `30 - New Jersey` -  `32 - New York` -  `33 - North Carolina` -  `35 - Ohio` -  `37 - Oregon` -  `38 - Pennsylvania` -  `40 - South Carolina` -  `43 - Texas` -  `44 - Utah` -  `47 - Washington` -  `48 - West Virginia` -  `49 - Wisconsin` -  `62 - Florida Commissioner of Deeds` 
    // String jurisdictionId
    test('to test the property `jurisdictionId`', () async {
      // TODO
    });

    // The name of the jurisdiction. Typically the state name.
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // When **true,** the name of the notary appears in the seal.
    // String notaryPublicInSeal
    test('to test the property `notaryPublicInSeal`', () async {
      // TODO
    });

    // When **true,** the name of the state appears in the seal.
    // String stateNameInSeal
    test('to test the property `stateNameInSeal`', () async {
      // TODO
    });


  });

}
