name: docusign_esignature_flutter_sdk
description: Implementation of DocuSign eSignature APIs in Flutter
version: 1.0.0
homepage: https://github.com/GiamBoscaro/docusign-sdk-openapi-generator#readme
documentation: https://github.com/GiamBoscaro/docusign-esignature-flutter-sdk#readme
repository: https://github.com/GiamBoscaro/docusign-esignature-flutter-sdk

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.1.8'

dev_dependencies:
  flutter_lints: '^2.0.1'
  test: '>=1.16.0 <1.18.0'
  copywriter: '^2.0.0'
  flutter_dotenv: '^5.0.2'

flutter:
